version: "3"

services:
  hugo:
    container_name: hugo_theme_iris
    image: ghcr.io/peaceiris/hugo:v${HUGO_VERSION}-mod
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src/hugo-theme-iris
      - ${HUGO_CACHEDIR}:/tmp/hugo_cache
    stdin_open: true
    tty: true
    working_dir: /src/hugo-theme-iris/exampleSite
    entrypoint: bash
